name: Go

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
  workflow_call:

jobs:
  call_build_test:
    uses: Fenrikur/reg-workflows/.github/workflows/build-test-go.yml@main
    with:
      base-directory: ./reg-attendee-service
      pact-client-repo: eurofurence/reg-attendee-transferclient
