name: Go

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: ./reg-attendee-service

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...
      working-directory: ./reg-attendee-service

    - name: Checkout eurofurence/reg-attendee-transferclient for contract tests
      uses: actions/checkout@v2
      with:
        repository: eurofurence/reg-attendee-transferclient
        path: reg-attendee-transferclient

    - name: Build eurofurence/reg-attendee-transferclient
      run: go build -v ./...
      working-directory: ./reg-attendee-transferclient

    - name: Test eurofurence/reg-attendee-transferclient
      run: go test -v ./...
      working-directory: ./reg-attendee-transferclient

    - name: Test
      run: go test -v ./...
      working-directory: ./reg-attendee-service
